/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProjectIndexRouteImport } from './routes/_auth/project/index'
import { Route as AuthProjectIdRouteImport } from './routes/_auth/project/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectIndexRoute = AuthProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProjectIdRoute = AuthProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$id': typeof AuthProjectIdRoute
  '/project': typeof AuthProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$id': typeof AuthProjectIdRoute
  '/project': typeof AuthProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/project/$id': typeof AuthProjectIdRoute
  '/_auth/project/': typeof AuthProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project/$id' | '/project'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$id' | '/project'
  id: '__root__' | '/' | '/_auth' | '/_auth/project/$id' | '/_auth/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/project/': {
      id: '/_auth/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthProjectIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/project/$id': {
      id: '/_auth/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthProjectIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthProjectIdRoute: typeof AuthProjectIdRoute
  AuthProjectIndexRoute: typeof AuthProjectIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProjectIdRoute: AuthProjectIdRoute,
  AuthProjectIndexRoute: AuthProjectIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
